import type { Metadata } from "next";
<<<<<<< HEAD
import { Outfit, Inter } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
>>>>>>> 0a60537ae4406588589c9ad6e83de11ebfaf93c1
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Firehawk Analytics — Build Your Advantage. Protect Your Growth.",
  description: "Firehawk Analytics provides the insights to lead your market and the custom architecture to secure it.",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 0a60537ae4406588589c9ad6e83de11ebfaf93c1
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${outfit.variable} ${inter.variable} font-sans antialiased`}
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>>>>>>> 0a60537ae4406588589c9ad6e83de11ebfaf93c1
      >
        {children}
      </body>
    </html>
  );
}
